### ISSUE TITLE
Użycie prymitywów zamiast klas opakowujących w repozytorium

### ISSUE THREAD

**Issue by DuDiiC** [sikor272/GoBooks#6]
W metodach zwracających wartości logiczne z repozytorium użytkowników, można zamienić użycie `Boolean` na typ prymitywny `boolean`. W przypadku tych metod nie ma ryzyka zwrócenia `null`a, zatem `Boolean` jest nadmiarowy.

https://github.com/sikor272/GoBooks/blob/5852fa2c34a23bb0798d3d28a5d817b6fc090ff6/src/main/java/pl/umk/mat/gobooks/users/UserRepository.java#L12-L14

Pozwoli to na uproszczenie warunków wewnątrz instrukcji `if`:

https://github.com/sikor272/GoBooks/blob/5852fa2c34a23bb0798d3d28a5d817b6fc090ff6/src/main/java/pl/umk/mat/gobooks/auth/AuthService.java#L50

https://github.com/sikor272/GoBooks/blob/5852fa2c34a23bb0798d3d28a5d817b6fc090ff6/src/main/java/pl/umk/mat/gobooks/auth/AuthService.java#L53

**Comment by sikor272** [comment]
Naprawione
